### ISSUE TITLE
Doesn't recognize scroll when html & body height are 100%

### ISSUE THREAD

**Issue by JoeFusco** [WickyNilliams/headroom.js#127]

**Comment by daviddk** [comment]
Also having this issue. If I remove height: 100% it works fine, but then other layout stuff is broken of course.

**Comment by WickyNilliams** [comment]
Could you create a reduced test case please? That would help in debugging the issue

**Comment by daviddk** [comment]
Of course:
http://codepen.io/anon/pen/myRovG

It seems that adding this height 100% alone doesn't cause the issue directly. Only when used together with the overflow property. 

Sadly I need both of these properties on my html and body to fix this other weird issue chrome has with background-attachment: fixed. 

Thanks for looking into it and taking the time Nick!

**Comment by WickyNilliams** [comment]
If i remove `overflow:auto` from the `html,body` rule, it works. Is that a possible fix?

**Comment by daviddk** [comment]
As stated before, I need both properties on the body and html rule. If removed issues with elements that have a background-attachment:fixed won't work in Chrome. 

But I'm not sure why headroom would break if these properties are applied?

**Comment by nonameolsson** [comment]
I'm also having this problem.. Any solution?

**Comment by cimocimocimo** [comment]
Using the codepen provided above I changed overflow: auto to overflow: visible and headroom started to work correctly. The background attachment also continued to work. Perhaps that could work for you daviddk?

I had a similar issue with 100% height and was able to fix it by setting the 'scroller' option to an element other than window (the default). I found that when I was setting html and body height: 100% the window object wasn't emitting scroll events since it wasn't moving on scroll. I just set scroller to another element on the page that was emitting scroll events.

**Comment by WickyNilliams** [comment]
Seems like @cimocimocimo's solution is probably better than working around it in Headroom. Closing

**Comment by wasabigeek** [comment]
@cimocimocimo any advise on identifying other elements that emit scroll events? I ran into the same issues while trying to implement this: https://www.eventbrite.com/engineering/mobile-safari-why/

**Comment by cimocimocimo** [comment]
Not off the top of my head, it's been a while since I dealt with this issue. If I recall correctly I think the html and body elements were sized with 100% height so they were taking the size of the viewport. I found the element that was scrolling was the main content container div. I think I just found that through the inspector to find the element in the hierarchy that had the total height of the scrolling content. It was a bit of trial and error as well. Hope this helps.

**Comment by luoye00** [comment]
> Using the codepen provided above I changed overflow: auto to overflow: visible and headroom started to work correctly. The background attachment also continued to work. Perhaps that could work for you daviddk?
> 
> I had a similar issue with 100% height and was able to fix it by setting the 'scroller' option to an element other than window (the default). I found that when I was setting html and body height: 100% the window object wasn't emitting scroll events since it wasn't moving on scroll. I just set scroller to another element on the page that was emitting scroll events.

This works for me , should set the 'scroller' dom  which scrolls on the page
