### ISSUE TITLE
Page content snaps up/down when headroom shows/hides

### ISSUE THREAD

**Issue by aleemb** [WickyNilliams/headroom.js#161]
Unlike the example in this repo, my nav bar about 300 pixels from the top (below ad/logo, etc) and I have it bound to headroom.js.

When the user scrolls down and back up, the nav goes from relative to absolute position (it appears on top). This causes the space occupied by the nav to disappear (since it is now absolutely positioned and no longer occupying space below the ad/logo). The causes content to jerk up some 40 pixels (height of nav). This is very jarring for readers while reading and scrolling up.

It would be nice if the nav was replaced with a transparent placeholder of the same height to avoid this behaviour.

Hope that makes sense and thanks for the lovely lib.

**Comment by WickyNilliams** [comment]
Is this something you could do yourself with the onPin onUnpin hooks? Seems like ideal use case thay avoids bloating the lib. I won't be adding this feature directly

**Comment by aleemb** [comment]
@WickyNilliams Thanks for the prompt response. Implementing it via the callback should be easy. 

However, this also means that Headroom.js is designed to exclusively support elements that are flush top. Anything else will be plagued by this bug, which is a bummer.

**Comment by WickyNilliams** [comment]
It's not designed to exclusively support elements flush top. I've used with elements on bottom and side for instance. It works better with elements that aren't position static/relative for reasons you outlined above, but with callbacks to allow more adventurous efforts (such as yours). 

If you're worried about code reuse then you can create a helper function that delegates to headroom. Yours is not a common use case - it is the first time this has been requested in 2 years since release (as far as I remember).

**Comment by globalworming** [comment]
then let this be marked as the second request :) I am too struggling with this problem

**Comment by TheMangoTrain** [comment]
Dynamically switching your nav from relative position to fixed or absolute, removes it from the page flow, so the page will adapt and jerk upwards, as is the nature of HTML.

You need to have a dummy element take the place of your nav, having the same height, in order to maintain the original page flow. Enable/disable the dummy element at the same time you switch the nav between relative/non-relative.
