### ISSUE TITLE
Using one selector for multiple sections 

### ISSUE THREAD

**Issue by adi8i** [WickyNilliams/headroom.js#163]
Wondering if is possible to use the same selector in multiple sections, for example. My selector is `.headroom` :  `var myElement = document.querySelector(".headroom");` . I add this class to navigation section, so it will be fine, now if i will add same class to one more section, only navigation will  work fine, .

Or the reverse, may i add 2 selectors in the same script ? like: `var myElement = document.querySelector(".headroom .my-class");`    ?

I've tried this and seems that dosen't work, i am asking here, maybe i miss something :)

**Comment by WickyNilliams** [comment]
Hey. For the first question, I assume you mean to use querySelectorAll? In that case instantiate a new instance of Headroom for each element. Something like this will do:

```js
var elements = document.querySelectorAll(".headroom");
var headrooms = Array.prototype.map.call(elements, function(element) {
  return new Headroom(element);
});

// or with jquery 
$(".headrooom").headroom();
```
For the second question, since it will select only a single element, this should still work exactly as described in the documentation. 

Apologies if there are slight syntactical error in the code above, I typed it out on my phone. Hopefully you get the gist.
