### ISSUE TITLE
Extending the library for both fixed on and offcanvas functionality simultaneously

### ISSUE THREAD

**Issue by chrisblakley** [WickyNilliams/headroom.js#187]
I implemented headroom.js on one of my projects last night and I instantly fell in love. I thought it'd be nice to have the navigation stick to the top of the page until it would have naturally been scrolled passed (as if headroom was not being used). Then it would move offcanvas and use the normal headroom functionality.

Here's a codepen to show it better: http://codepen.io/chrisblakley/pen/gaZzeY

The only requirement for this is to declare a header so a padding-top "buffer" can be applied. However, if a header is not declared, the body could be used as a fallback.

At the bottom of the JS panel in that codepen is the scroll listener for my ```.headroom--below``` class. Very simple- if the scroll position is greater than the offset top of the header + the height of the header (in case it isn't the first element in the document).

Here's the implementation on my project with the idea pushed a little further: https://gearside.com/nebula/

Hopefully I explained my thought well enough, and if the feature doesn't make it into the library, maybe it'll help some other devs looking to do something similar.

**Comment by WickyNilliams** [comment]
Hey! 

I've done something like this before, and this is exactly how I did it :) I've also used headroom to mimic functionality of the bootstrap affix plugin (sidebar becomes `position:fixed` after a certain point).

I won't add anything official to the lib in an official capacity, because really there's not that much to it, and any addition would likely be limiting in some circumstances. Good to have this written up here for anybody else interested in the approach.

Cheers
