### ISSUE TITLE
Bower install not working

### ISSUE THREAD

**Issue by pensierinmusica** [WickyNilliams/headroom.js#225]
The bower install instructions you provide [in the docs](https://github.com/WickyNilliams/headroom.js#install-with-bower) don't seem to work:

```
bower EHTTP         Status code of 500
```

Also, trying to install directly from the Github repo:

```
bower install --save git://github.com/WickyNilliams/headroom.js.git
```

Doesn't work and produces:

```
bower invalid-meta  The "main" field cannot contain minified files
bower invalid-meta  The "main" field has to contain only 1 file per filetype; found multiple .js files: ["dist/headroom.js","dist/headroom.min.js","dist/jQuery.headroom.js","dist/jQuery.headroom.min.js","dist/angular.headroom.js","dist/angular.headroom.min.js"]
```

Can you please check both things and fix them? Btw, wouldn't it be easier simply [publishing a standard Bower package](http://bower.io/docs/creating-packages/#register)?

Thx!

**Comment by omgaz** [comment]
https://npmcdn.com/headroom.js@0.9.3/bower.zip

Server error: ENOENT: no such file or directory, lstat '/tmp/npm-http-server-headroom.js@0.9.3/tmp/npm-http-server-headroom.js@0.9.3/bower.zip'

**Comment by WickyNilliams** [comment]
It's working fine for me. Wonder if it was a temporary issue with npmcdn?

![screen shot 2016-06-02 at 14 36 27](https://cloud.githubusercontent.com/assets/1091390/15746674/7497a51e-28cf-11e6-9c13-26a2d7eb83e3.png)

I don't use the regular bower registry because it (unwisely IMO) forces you to commit build artefacts, which causes endless confusion with PRs, making contributions more difficult.

**Comment by WickyNilliams** [comment]
The warnings can safely be ignored. I think I will eventually remove the minified files though
