### ISSUE TITLE
Setup via Bower doesn't work

### ISSUE THREAD

**Issue by thasmo** [WickyNilliams/headroom.js#236]
Bower installs some files but there're only some files like `LICENSE`, `README.md` etc. - missing all the JS files.

**Comment by galengidman** [comment]
+1.

This is because all the Bower files are in `/dist`, which is ignored in `.gitignore`.

**Comment by rogatty** [comment]
Readme tells us to use:
```
bower install https://npmcdn.com/headroom.js/bower.zip --save
```
but this way we can't lock to a specific version. I'm treating it as a blocker for the upgrade.

**Comment by WickyNilliams** [comment]
This should do it:

```js
bower install https://npmcdn.com/headroom.js@0.9.3/bower.zip --save
```

**Comment by thasmo** [comment]
True, that's working of course. @WickyNilliams, what's the reason for not supporting the bower registry?

**Comment by WickyNilliams** [comment]
Bower forces you to commit build artefacts to your repository. This creates needless churn in git history. It also causes endless confusion in pull requests:

* contributors update the build artefacts instead of the source
* contributors build project and commit the artefacts, which should only be done on version bump, not per PR.

When these things happen, it can create lots of back and forth between myself and contributor. Given we're all doing this in our spare time, it can drag a PR out for days/weeks/months (especially because i'm not always the most active maintainer). 

npmcdn makes supporting bower easier for myself and contributors. Though, given all the issues I get about this, it seems to have caused confusion with consumers of the library. I honestly didn't realise so many people used bower!

I don't understand why anyone would prefer/choose bower over npm, apart from legacy reasons. Each to their own, of course.

**Comment by thasmo** [comment]
Thanks for explaining, totally legit and understandable. Bower e.g. let's me define dependencies even if they're not available on GitHub or NPM. I can just configure an URL, e.g. resources from `npmcdn.com`. As far as I know I can't use `package.json` for defining dependencies which are not available on the npm registry. I dunno why, but I'm used to define project dependencies via bower (e.g. libraries, assets, scripts, etc.) and using `package.json` for defining development dependencies (e.g. gulp, browser-sync, ec.).
