### ISSUE TITLE
Bower does not work

### ISSUE THREAD

**Issue by valeriosillari** [WickyNilliams/headroom.js#268]
Today running bower and i got an error.
Until the day before i was working.

if you set bower to the path as in the repo readme ( https://unpkg.com/headroom.js/bower.zip ) you got a message error:
**Not found: file "/bower.zip" in package headroom.js@0.9.3**

anyone has the same issue?

**Comment by MartynWynne** [comment]
Got the same issue here as well

**Comment by bchew** [comment]
We got the same issue today as well, it looks like the `bower.zip` file is gone from the CDN. Temporarily resolved it by zipping up the extracted copy which we had locally and uploaded it while this is resolved. Attaching what we used if anyone wants to use it for now.
[bower.zip](https://github.com/WickyNilliams/headroom.js/files/950268/bower.zip)

**Comment by valeriosillari** [comment]
ok for a temporary solution. but i need to have a valid bower packages for running bower on server side for deploying my application.

I guess the bower installation should be fixed in the repo itself.

**Comment by mete89** [comment]
Agree with @valeriosillari

**Comment by laantorchaweb** [comment]
any updates about this issue @WickyNilliams ? is there anything that we can do to help?

**Comment by WickyNilliams** [comment]
It seems that unpkg has dropped support for bower. I'd be inclined to also do the same. Bower support has given me lots of headaches, and in my view has lost to npm and is dying as a result.

With that in mind, I may drop any sort of official support for bower.

**Comment by laantorchaweb** [comment]
ok, that's fine I guess, everyone is moving out of bower, although I'm using this library trough `ember-headroom` and I guess there are other wrappers around this plugin somewhere else.

**Comment by valeriosillari** [comment]
ok fair enough.
we can use npm.

just let us know if you want to remove bower files and bower installation info from the repo, or we can also help and set a pull request for it.

**Comment by reco** [comment]
is there no way to fix this in the repo itself? also need a fix for this

**Comment by them-es** [comment]
Since installing a single file via URL is [supported in Bower](https://bower.io/#install-packages) you can do

`bower install https://unpkg.com/headroom.js/dist/headroom.min.js --save`

The generated `index.js` file contains the minified version of headroom.js

**Comment by dangelion** [comment]
Solved adding this to your bower.json:
`"headroom.js": "https://github.com/WickyNilliams/headroom.js/files/950268/bower.zip"
`

**Comment by WickyNilliams** [comment]
I'm going to remove bower support, as it has been deprecated. @them-es' solution should work for anyone still using it

**Comment by klaslundberg** [comment]
I'd be super happy if there would be proper bower support, since bower is still working like charm even if they are maintaining it. All it would take is really to include the dist-files when making a github release, like most other javascript repos/packages do. A really simple way to solve the problem.

**Comment by WickyNilliams** [comment]
You can continue using it, as described above. In practical terms, it's exactly the same. 

I hate to say no, but bower support has historically proven tricky (not least because people keep accidentally committing dist files when making a PR). I have limited time for maintenance, and bower support is not a valuable use of my time.

Out of curiosity, why are you still using bower?

**Comment by dennisfrank** [comment]
@WickyNilliams. I fully understand your reasons.

On newer projects I use npm. But I take care of multiple older projects that use Bower without any issue. There is no need to change the build process for these projects. It feels a bit strange when a ressource you were relying on previously is suddenly missing while building the project. It seems this costs several developers a few hours. 

As long as @them-es solution work 8https://github.com/WickyNilliams/headroom.js/issues/268#issuecomment-302870293) I can work with that.

Thanks for your work @WickyNilliams! 😃

**Comment by klaslundberg** [comment]
My strongest reasons for using Bower for distributed libs is:
- You can install from most sources, you don't need to depend on a whole system behind it (even if they have a search engine etc).
- It works terrific with GitHub and GitHub releases, especially for versioning/upgrading or making a fork (which I likely will do with this repo).
- Upgrading/maintaining packages from a client perspective is as easy as it can be.

Regarding NPM for example, it's great for build tools etc and a nightmare for managing your distributed libs.

NPM on the other hand is perfect for Node.js projects. So, I use Bower for the external libs I include in HTML projects and NPM for all my building tools and Node.js projects.

And yes, it's very possible to install from the CDN, but then I likely will have to look for new versions manually, instead of having the nice built in version management that comes with bower + github.
