### ISSUE TITLE
Class .headroom-pinned not added after page reload

### ISSUE THREAD

**Issue by dev4q1** [WickyNilliams/headroom.js#289]
Hi,

I noticed that after a page reload and when scrolling up the class .headroom-pinned isn't added to the DOM element. You have first to scroll down and then scroll up to trigger this class add.

Is this a wanted/normal behaviour?

Thanks for your help!

**Comment by dev4q1** [comment]
I am using headroom v0.9.4

**Comment by WickyNilliams** [comment]
This is by design, so that header doesn't get hidden or anything like that on page load.

**Comment by zackpyle** [comment]
@dev4q1 I agree with you

@WickyNilliams I don't see how this is true... If you refresh while in the middle of a page, then IMO, it should show the not-top and pinned classes. And if it's already at the top (initial load or refresh at top) then it doesn't matter because it gets the pinned class there too until you scroll.

I guess it depends on what styles you have set for pinned not-top though? Maybe this should be an attribute you can add to the options array?

@dev4q1 - Anyway, I just used js to add .headroom--pinned to the header on load to make sure it loads correctly 🤷🏼‍♂️
