### ISSUE TITLE
NPM package is not up to date

### ISSUE THREAD

**Issue by brunostasse** [WickyNilliams/headroom.js#328]
I noticed the NPM package is out of sync with the repo, since it hasn't been updated in two years. This is a problem as recent improvements are very useful. Could it be done?

Thanks for this great widget!

**Comment by WickyNilliams** [comment]
Hey. Yes, this has been an intentional choice. I wanted to gather a bunch of fixes, features, and code improvements into one release.

I'm currently tweaking the code to reduce the library's size. Despite all the latest changes/fixes, i think i'll be able to shave 10-20% off :) I'm almost done, and it should be released in the next week.

**Comment by WickyNilliams** [comment]
I just published v0.10.0 to npm :tada:
